#!/bin/sh

# ip link set eth0 up
# udhcpc -i eth0

# echo "https://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
# echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

apk add --no-cache \
    py3-pip \
    python3-dev \
    parted-dev \
    gcc \
    musl-dev \
    pacman \
    arch-install-scripts \
    coreutils \
    util-linux \
    pciutils \
    tzdata \
    git \
    dosfstools \
    device-mapper \
    btrfs-progs \
    e2fsprogs \
    f2fs-tools \
    xfsprogs \
    cryptsetup \
    lvm2

pip install --break-system-packages pyparted
