#!/bin/bash
# shellcheck disable=SC1091,SC2154,SC2086

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_GLOB="archinstoo-*.pkg.tar.zst"

go_to () {
	cd "$SCRIPT_DIR/archinstoo" || exit 1
}

pre_build () {
    rm -f ./*-any.pkg.tar.zst
}

clean () {
    rm -rf pkg src dist ./*.pkg.tar.zst.sig build ./*.egg-info ../*.egg-info ./*-git
} # make sure no old sigs or build artifacts

sign () {
    gpg --detach-sign $PKG_GLOB
}
verif() {
    gpg --verify $PKG_GLOB.sig
}

case "$1" in
	-t | --tree)
	go_to
	{
		echo '# Project Structure'
		echo '```'
		tree -F -I '*.po|*.pyc|*.mo|*.png|*.svg|locales|docs|logs|__pycache__|__init__.py' | sed 's/\.py//g'
		echo '```'
	} > docs/README.md
	;;
	-c | --clean)
	go_to
	clean && pre_build
	;;
	-b | --build)
	go_to
	pre_build
	makepkg -Cf
	clean
	;;
	-s | --sign)
	go_to
	sign
	;;
	-sv | --verify-sig)
	go_to
	verif
	;;
	-i|--install)
	go_to
 	$ELEV pacman -U --overwrite '*' $PKG_GLOB
	;;
	-ul | --up-logs)
	go_to
	curl -F 'file=@./logs/install.log' https://0x0.st
	;;
	-gl | --grep-logs)
	go_to
	grep -i "$2" ./logs/install.log
	;;
	-gc | --grep-code)
	go_to
	git grep -ni "$2"
	;;
    -tf | --test-full)
    ./RUN --config examples/config-sample-full.json
    ;;
	-h2t | --host-to-target)
	go_to
	. ./PKGBUILD
	if [ "$2" = "-o" ] || [ "$2" = "--opt" ]; then
		$ELEV pacman -Sy --needed "${depends[@]}" "${optdepends[@]}"
	else
		$ELEV pacman -Sy --needed "${depends[@]}"
	fi
	;;
	*)
	# Pass through to archinstoo
	./RUN "$@" --advanced --debug
	;;
esac
