#!/bin/sh

# Fedora bootstrap for archinstoo
# Run as root from a minimal Fedora install or live environment

# shellcheck disable=SC2046
dnf install --assumeyes --setopt=install_weak_deps=False $(awk '{print $1}' << 'PKGS'
    ca-certificates             # https support
    python3                     # runtime
    python3-pip                 # pip
    python3-devel               # python headers
    parted                      # libparted
    parted-devel                # libparted headers
    gcc                         # c compiler
    pacman                      # arch package manager
    arch-install-scripts        # pacstrap, genfstab, etc
    coreutils                   # gnu core utils
    util-linux                  # lsblk, blkid, etc
    pciutils                    # lspci
    tzdata                      # timezone data
    dosfstools                  # mkfs.fat
    device-mapper               # dm-* devices
    e2fsprogs                   # mkfs.ext4
    cryptsetup                  # luks
    lvm2                        # lvm
    btrfs-progs                 # btrfs
    f2fs-tools                  # f2fs
    xfsprogs                    # mkfs.xfs
PKGS
)

pip install --break-system-packages pyparted
