#!/bin/bash
# shellcheck disable=SC1091,SC2154
if [ "$(id -u)" = "0" ]; then
    ELEV=""
else
    ELEV="${ELEV:-sudo}"
fi
# help / list / size 
# do not need root but we append it for most features
# can be launched with ELEV=doas env var
(cd archinstoo && $ELEV python -B -m archinstoo "$@") && cd ..
