# This workflow will build Python packages on every commit.

name: Build archinstoo

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman --noconfirm -Syyu
          pacman --noconfirm -Sy python-setuptools python-pip python-build
          pacman --noconfirm -Sy python-pyparted
      - name: Remove existing archinstall (if any)
        run: pip uninstall -y archinstoo --break-system-packages || true
      - name: Build archinstoo
        run: python -m build --wheel archinstoo
      - name: Install archinstoo
        run: pip install archinstoo/dist/*.whl --break-system-packages --no-deps
      - name: Run archinstoo
        run: |
          python -V
          archinstoo --help
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: archinstoo
          path: archinstoo/dist/*
